### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by Tachi107** [CameronLonsdale/MTP#19]
Hi, it is currently impossible to run `mtp` with new Python versions, as `getargspec` got removed in Python 3.11.

I've been able to run the tool by editing `~/.local/pipx/venvs/mtp/lib/python3.11/site-packages/urwid/split_repr.py` on my machine, but that's probably not the best solution. Also see <https://github.com/Pylons/pyramid/issues/3688>.

Here's the traceback when running `mtp` after a fresh install with `pipx` on Debian 12:

	$ mtp
	Traceback (most recent call last):
	  File "/home/tachi/.local/bin/mtp", line 5, in <module>
	    from cli import main
	  File "/home/tachi/.local/pipx/venvs/mtp/bin/cli.py", line 6, in <module>
	    from manytime import many_time_pad_attack
	  File "/home/tachi/.local/pipx/venvs/mtp/lib/python3.11/site-packages/manytime/__init__.py", line 6, in <module>
	    from manytime.interactive import interactive
	  File "/home/tachi/.local/pipx/venvs/mtp/lib/python3.11/site-packages/manytime/interactive.py", line 6, in <module>
	    import urwid
	  File "/home/tachi/.local/pipx/venvs/mtp/lib/python3.11/site-packages/urwid/__init__.py", line 26, in <module>
	    from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
	  File "/home/tachi/.local/pipx/venvs/mtp/lib/python3.11/site-packages/urwid/widget.py", line 36, in <module>
	    from urwid.split_repr import split_repr, remove_defaults, python3_repr
	  File "/home/tachi/.local/pipx/venvs/mtp/lib/python3.11/site-packages/urwid/split_repr.py", line 24, in <module>
	    from inspect import getargspec
	ImportError: cannot import name 'getargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)

**Comment by Tachi107** [comment]
Upgrading `urwid` to version 2.1.0 or newer would solve the issue (see https://github.com/MrIndeciso/MTP/commit/ba12657b0ef830bc9c98dcb0208778a24ee70a02 and <https://urwid.org/changelog.html#urwid-2-1-0>)

**Comment by CameronLonsdale** [comment]
Worth upgrading, feel free to bump the version & test that it still works and raise a PR. Otherwise I will take a look soon and if its easy just bump it and push a new version to PyPi

**Comment by CameronLonsdale** [comment]
Uploaded a new version to Pypi, you can either upgrade or fresh reinstall https://pypi.org/project/mtp/1.1.0/

**Comment by Tachi107** [comment]
Thanks for the fast fix!
