### ISSUE TITLE
Error on library

### ISSUE THREAD

**Issue by MicheleSottocasa** [CameronLonsdale/MTP#21]
Python return me these error when I try to use the library

```
Traceback (most recent call last):
  File "C:\python\python-3.10.5\lib\runpy.py", line 196, in _run_module_as_main  
    return _run_code(code, main_globals, None,
  File "C:\python\python-3.10.5\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\python\python-3.10.5\Scripts\mtp.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'cli'
```

**Comment by histefanhere** [comment]
Same issue. Running Python 3.10.2

**Comment by CameronLonsdale** [comment]
Not entirely sure why this might be. Are you installing with `pip3 install mtp` and using the script via `mtp examples/sample.ciphertexts` for example?

**Comment by histefanhere** [comment]
Yep, more specifically `python -m pip install mtp` where `python` goes to my 3.10.2 instance, and I've cloned the repository and ran that command with the same error output:

![image](https://user-images.githubusercontent.com/23431724/236182014-412a888e-a6f4-46ca-9723-c6edefe08b5b.png)

**Comment by DarkOriole4** [comment]
Same problem here (Python 3.9.2)

**Comment by Badesha02** [comment]
> Yep, more specifically `python -m pip install mtp` where `python` goes to my 3.10.2 instance, and I've cloned the repository and ran that command with the same error output:
> 
> ![image](https://user-images.githubusercontent.com/23431724/236182014-412a888e-a6f4-46ca-9723-c6edefe08b5b.png)

use this command - pip install pyCLI

**Comment by Mik1810** [comment]
Still doesn't work

**Comment by teotexe** [comment]
Any fix found so far?

**Comment by Mik1810** [comment]
Yes, i have forked your repo and made a fix

Il dom 10 mar 2024, 19:01 Matteo Tacconi ***@***.***> ha
scritto:
